name: CI/CD Pipeline

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]

jobs:
  build-auth:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: "maven"
      - name: Build Auth Server
        run: cd authorization-server && chmod +x mvnw && ./mvnw clean package -DskipTests

  build-resource:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: "maven"
      - name: Build Resource Server
        run: cd resource-server && chmod +x mvnw && ./mvnw clean package -DskipTests

  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: ag-prueba-front/package-lock.json
      - name: Install Dependencies
        run: cd ag-prueba-front && npm ci
      - name: Build Angular
        run: cd ag-prueba-front && npm run build -- --configuration=production

  deploy-simulation:
    needs: [build-auth, build-resource, build-frontend]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Simulate Deployment
        run: echo "Desplegando versión ${{ github.sha }} a producción..."
