name: CI/CD Pipeline

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]

jobs:
  build-auth:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with: { java-version: "17", distribution: "temurin", cache: "maven" }

      - name: Check Outdated Dependencies
        run: cd authorization-server && chmod +x mvnw && ./mvnw versions:display-dependency-updates
        continue-on-error: true

      - name: Run Checkstyle
        run: cd authorization-server && chmod +x mvnw && ./mvnw checkstyle:check
        continue-on-error: true
      - run: cd authorization-server && chmod +x mvnw && ./mvnw clean package

      - name: Generate SBOM (Auth Server)
        uses: anchore/sbom-action@v0
        with:
          path: authorization-server
          format: spdx-json
          output-file: authorization-server-sbom.spdx.json

      - name: Upload SBOM Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom-auth-server
          path: authorization-server-sbom.spdx.json

  build-resource:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with: { java-version: "17", distribution: "temurin", cache: "maven" }

      - name: Check Outdated Dependencies
        run: cd authorization-server && chmod +x mvnw && ./mvnw versions:display-dependency-updates
        continue-on-error: true

      - name: Run Checkstyle
        run: cd resource-server && chmod +x mvnw && ./mvnw checkstyle:check
      - run: cd resource-server && chmod +x mvnw && ./mvnw clean package -DskipTests

  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          {
            node-version: "18",
            cache: "npm",
            cache-dependency-path: "ag-prueba-front/package-lock.json",
          }
      - run: cd ag-prueba-front && npm ci

      - name: Check Outdated Dependencies
        run: cd ag-prueba-front && npm outdated
        continue-on-error: true

      - name: Run ESLint
        run: cd ag-prueba-front && npm run lint
        continue-on-error: true
      - run: cd ag-prueba-front && npm run build -- --configuration=production

      - name: Generate SBOM (Frontend)
        uses: anchore/sbom-action@v0
        with:
          path: ag-prueba-front
          format: spdx-json
          output-file: frontend-sbom.spdx.json

      - name: Upload SBOM Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom-frontend
          path: frontend-sbom.spdx.json

  deploy-simulation:
    needs: [build-auth, build-resource, build-frontend]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/master'
    steps:
      - run: echo "Desplegando versión ${{ github.sha }} a producción..."
